/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.iptv.view;

import br.com.iptv.dao.ClientesDAO;
import br.com.iptv.dao.Utilitarios;
import br.com.iptv.jdbc.ConfigDB;
import br.com.iptv.model.Clientes;
import java.awt.event.KeyEvent;
import java.sql.Date;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.List;
import static javax.print.attribute.Size2DSyntax.MM;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Giovane Oliveira
 */
public class IPTVadministrator extends javax.swing.JFrame {

    static int c;

    /**
     * Creates new form IPTVadministrator
     */
    public IPTVadministrator() {
        initComponents();
        checkFilter.setSelected(false);
        txtCodigo.setEnabled(false);
       new ClientesDAO().aniversariante();

    }

    public boolean verificarCampos() {
        boolean confirma;
        if (txtNome.getText().trim().isEmpty() || txtDataVencimento.getText().replace("/", "").trim().isEmpty() || txtDataSistema.getText().trim().isEmpty()) {

            //txtObs.getText().trim().isEmpty() 
            JOptionPane.showMessageDialog(null, "Preencha os campos");
            confirma = true;
        } else {

            confirma = false;

        }

        return confirma;

    }

    public void listarClientesPagamanto() {

        ClientesDAO dao = new ClientesDAO();
        List<Clientes> lista = dao.listarClientesPagamento(c);
        DefaultTableModel dados = (DefaultTableModel) TclientesPag.getModel();
        dados.setNumRows(0);
        for (Clientes c : lista) {

            dados.addRow(new Object[]{
                c.getId(),
                c.getNOME(),
                c.getDATAVENCIMENTO(),
                c.getDATAVENCSISTEMA(),
                c.getOBS(),
                c.getFORMAPAG()

            });
        }

    }

    public void listarClientesPagamantoSis() {

        ClientesDAO dao = new ClientesDAO();
        List<Clientes> lista = dao.listarClientesSistemaPagamento(c);
        DefaultTableModel dados = (DefaultTableModel) TpagSis.getModel();
        dados.setNumRows(0);
        for (Clientes c : lista) {

            dados.addRow(new Object[]{
                c.getId(),
                c.getNOME(),
                c.getDATAVENCIMENTO(),
                c.getDATAVENCSISTEMA(),
                c.getOBS(),
                c.getFORMAPAG()

            });
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tmenu = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtLucro = new java.awt.Label();
        jPanel7 = new javax.swing.JPanel();
        txtCusto = new java.awt.Label();
        jPanel8 = new javax.swing.JPanel();
        txtCreditos = new java.awt.Label();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        jScrollPane2 = new javax.swing.JScrollPane();
        TclientesPag = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        TpagSis = new javax.swing.JTable();
        checkFilter = new javax.swing.JCheckBox();
        txtCredito = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPesquisa = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        Pcadastro = new javax.swing.JPanel();
        label7 = new java.awt.Label();
        txtNome = new java.awt.TextField();
        label8 = new java.awt.Label();
        label9 = new java.awt.Label();
        label10 = new java.awt.Label();
        label11 = new java.awt.Label();
        label12 = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObs = new javax.swing.JTextArea();
        comboPix = new javax.swing.JComboBox<>();
        btnCadastrar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        txtDataVencimento = new javax.swing.JFormattedTextField();
        txtDataSistema = new javax.swing.JFormattedTextField();
        txtCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTempo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setText("Clientes que vencem hoje no sistema");

        jLabel2.setText("Clientes que vencem hoje");

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        txtLucro.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        txtLucro.setForeground(new java.awt.Color(255, 255, 255));
        txtLucro.setText("000000");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(txtLucro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txtLucro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));

        txtCusto.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        txtCusto.setForeground(new java.awt.Color(255, 255, 255));
        txtCusto.setText("000000");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(txtCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(txtCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        txtCusto.getAccessibleContext().setAccessibleName("");

        jPanel8.setBackground(new java.awt.Color(0, 0, 0));

        txtCreditos.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        txtCreditos.setForeground(new java.awt.Color(255, 255, 255));
        txtCreditos.setText("000000");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(txtCreditos, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txtCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        label4.setText("Lucro");

        label5.setText("Custo");

        label6.setText("Creditos");

        TclientesPag.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "CODIGO", "NOME", "DATAVENC", "DATASIS", "OBS", "FORMAPAG"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TclientesPag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TclientesPagMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TclientesPag);

        TpagSis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "CODIGO", "NOME", "DATAVENC", "DATASIS", "OBS", "FORMAPAG"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TpagSis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TpagSisMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TpagSis);

        checkFilter.setText("Nao Filtrar");
        checkFilter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkFilterMouseClicked(evt);
            }
        });
        checkFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkFilterActionPerformed(evt);
            }
        });
        checkFilter.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                checkFilterPropertyChange(evt);
            }
        });

        txtCredito.setEditable(false);

        jButton1.setText("Informar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Créditos");

        jLabel5.setText("Pesquisar");

        txtPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisaActionPerformed(evt);
            }
        });
        txtPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPesquisaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisaKeyReleased(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(checkFilter)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnBuscar))
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(36, 36, 36))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(188, 188, 188)
                .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(165, 165, 165))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPanel4, jPanel7, jPanel8});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jScrollPane2, jScrollPane3});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(checkFilter)
                    .addComponent(txtCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jPanel4, jPanel7, jPanel8});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jScrollPane2, jScrollPane3});

        Tmenu.addTab("Dashboard", jPanel1);

        label7.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        label7.setText("Cadastro de Clientes");

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        label8.setText("Data Vencimento:");

        label9.setText("Nome:");

        label10.setText("Data Vencimento Sistema:");

        label11.setText("Observacao:");

        label12.setText("Forma de pagamento:");

        txtObs.setColumns(20);
        txtObs.setRows(5);
        jScrollPane1.setViewportView(txtObs);

        comboPix.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pix", "Boleto", "Dinheiro", "Deposito" }));

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        try {
            txtDataVencimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtDataSistema.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataSistemaActionPerformed(evt);
            }
        });

        txtCodigo.setEditable(false);
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });

        jLabel3.setText("Codigo:");

        txtTempo.setText("Data de Fidelidade");

        javax.swing.GroupLayout PcadastroLayout = new javax.swing.GroupLayout(Pcadastro);
        Pcadastro.setLayout(PcadastroLayout);
        PcadastroLayout.setHorizontalGroup(
            PcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PcadastroLayout.createSequentialGroup()
                .addGroup(PcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PcadastroLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PcadastroLayout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(btnCadastrar)
                        .addGap(60, 60, 60)
                        .addComponent(btnExcluir)
                        .addGap(60, 60, 60)
                        .addComponent(btnAlterar)))
                .addContainerGap(273, Short.MAX_VALUE))
            .addGroup(PcadastroLayout.createSequentialGroup()
                .addGroup(PcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PcadastroLayout.createSequentialGroup()
                        .addGroup(PcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PcadastroLayout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(PcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PcadastroLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(label12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(1, 1, 1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PcadastroLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(PcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboPix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtDataSistema, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtDataVencimento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                    .addGroup(PcadastroLayout.createSequentialGroup()
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89)
                        .addComponent(txtTempo)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        PcadastroLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAlterar, btnCadastrar, btnExcluir});

        PcadastroLayout.setVerticalGroup(
            PcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PcadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PcadastroLayout.createSequentialGroup()
                        .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addGroup(PcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(txtTempo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataSistema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboPix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(PcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        Tmenu.addTab("Cadastro", Pcadastro);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Tmenu, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Tmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // TODO add your handling code here:

        if (!verificarCampos()) {
            Clientes obj = new Clientes();
            obj.setNOME(txtNome.getText());
            obj.setDATAVENCIMENTO(txtDataVencimento.getText().replace('/', '-'));
            obj.setDATAVENCSISTEMA(txtDataSistema.getText().replace('/', '-'));
            obj.setOBS(txtObs.getText());
            obj.setFORMAPAG(comboPix.getSelectedItem().toString());

            if (new ClientesDAO().verificarNome(txtNome.getText())) {

                JOptionPane.showMessageDialog(null, "Este nome já existe em nossa base de dados");

            } else {
                new ClientesDAO().cadastrarCliente(obj);
                new Utilitarios().LimpaTela(Pcadastro);
                txtObs.setText(null);
                txtNome.setText(null);
                txtTempo.setText("Data de fidelidade");

            }

        }


    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:

       int input = JOptionPane.showConfirmDialog(null, "Deseja mesmo excluir este cadastro?");
        // 0=yes, 1=no, 2=cancel
        if(input == 0){
        new ClientesDAO().excluirCliente(Integer.parseInt(txtCodigo.getText()));

        new Utilitarios().LimpaTela(Pcadastro);
        txtObs.setText(null);
        txtNome.setText(null);
        txtTempo.setText("Data de fidelidade");

        }else{
        
        JOptionPane.showMessageDialog(null, "Cancelado");
        }
        
        

    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:

        if (!verificarCampos()) {
            
             int input = JOptionPane.showConfirmDialog(null, "Deseja mesmo alterar este cadastro?");
        // 0=yes, 1=no, 2=cancel
        if(input == 0){
        
            Clientes obj = new Clientes();
            obj.setId(Integer.parseInt(txtCodigo.getText()));
            obj.setNOME(txtNome.getText());
            obj.setDATAVENCIMENTO(txtDataVencimento.getText().replace('/', '-'));
            obj.setDATAVENCSISTEMA(txtDataSistema.getText().replace('/', '-'));
            obj.setOBS(txtObs.getText());
            obj.setFORMAPAG(comboPix.getSelectedItem().toString());
            new ClientesDAO().alterarCliente(obj);
            new Utilitarios().LimpaTela(Pcadastro);
            txtObs.setText(null);
            txtNome.setText(null);
            txtTempo.setText("Data de fidelidade");
        
        }else{
        
        JOptionPane.showMessageDialog(null, "Cancelado");
        
        }
           

        }

    }//GEN-LAST:event_btnAlterarActionPerformed

    private void txtDataSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataSistemaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataSistemaActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
      
           

    

        txtCredito.setText(new ClientesDAO().precoCredito().toString());
        listarClientesPagamanto();
        listarClientesPagamantoSis();
        ClientesDAO dao = new ClientesDAO();
        txtLucro.setText(NumberFormat.getCurrencyInstance().format(dao.fatura(1)));
        txtCusto.setText(NumberFormat.getCurrencyInstance().format(dao.fatura(2)));
        txtCreditos.setText(String.valueOf(dao.fatura(3)));


    }//GEN-LAST:event_formWindowActivated

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void TpagSisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TpagSisMouseClicked
        // TODO add your handling code here:
        Tmenu.setSelectedComponent(this.Pcadastro);
        txtCodigo.setText(TpagSis.getValueAt(TpagSis.getSelectedRow(), 0).toString());
        txtNome.setText(TpagSis.getValueAt(TpagSis.getSelectedRow(), 1).toString());
        txtDataVencimento.setText(TpagSis.getValueAt(TpagSis.getSelectedRow(), 2).toString().replace('-', '/'));
        txtDataSistema.setText(TpagSis.getValueAt(TpagSis.getSelectedRow(), 3).toString().replace('-', '/'));
        txtObs.setText(TpagSis.getValueAt(TpagSis.getSelectedRow(), 4).toString());
        comboPix.setSelectedItem(TpagSis.getValueAt(TpagSis.getSelectedRow(), 5).toString());
          //aniversario do cliente
      
        int ano = 0;
        int mes = 0;
        int dia = 0;
        if(!txtNome.getText().trim().isEmpty()){
         ano = Integer.parseInt(txtDataVencimento.getText().substring(6,10));
            mes = Integer.parseInt(txtDataVencimento.getText().substring(3,5));
            dia = Integer.parseInt(txtDataVencimento.getText().substring(0,2));
            
            //pegar a data do sistema 
             String data = LocalDate.now().toString();
       int ano1 = Integer.parseInt(data.substring(0, 4)); //ano
       
       int mes1 = Integer.parseInt(data.substring(5, 7)); //mes
        
       int dia1 = Integer.parseInt(data.substring(8, 10)); //dia
      
       
       // calculo data final
       int anoFinal = ano1 - ano;
       if(anoFinal < 0){
          anoFinal = ano - ano1;
       }
         int mesFinal = mes - mes1; 
         if(mesFinal  < 0){
         mesFinal =  mes1 - mes;
         }
       int diaFinal = dia1 - dia;
       if(diaFinal < 0){
       diaFinal =  dia - dia1;
       }
       if(mes < mes1 && anoFinal == 1){
           
txtTempo.setText("Cliente à " + " " + anoFinal + " ano " + mesFinal + " meses e " + " " + diaFinal + " dias");

       }else if(mes > mes1 && anoFinal == 1){
       
             txtTempo.setText(/*"Cliente à " + " " + anoFinal + " ano " +*/ mesFinal + " meses e " + " " + diaFinal + " dias");
       
       }else{
       
           txtTempo.setText("Cliente à " + mesFinal + " meses e " + " " + diaFinal + " dias" /*+ " " + anoFinal + " anos"*/);
       
       }
       
       
         
          
            
        
        }
    }//GEN-LAST:event_TpagSisMouseClicked

    private void checkFilterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkFilterMouseClicked
        // TODO add your handling code here:
        if (checkFilter.isSelected()) {
            c = 1;
            // do something...
            listarClientesPagamanto();
            listarClientesPagamantoSis();

        } else {

            c = 0;
            listarClientesPagamanto();
            listarClientesPagamantoSis();
            // do something else...

        }


    }//GEN-LAST:event_checkFilterMouseClicked

    private void checkFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkFilterActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_checkFilterActionPerformed

    private void checkFilterPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_checkFilterPropertyChange
        // TODO add your handling code here:

    }//GEN-LAST:event_checkFilterPropertyChange

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Jcredito().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaKeyPressed
        // TODO add your handling code here:

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            if (txtPesquisa.getText().trim().isEmpty()) {
                listarClientesPagamanto();
                listarClientesPagamantoSis();

            }
            List<Clientes> lista = new ClientesDAO().consultarClientesPorNome1(txtPesquisa.getText());
            DefaultTableModel dados = (DefaultTableModel) TclientesPag.getModel();
            dados.setNumRows(0);
            for (Clientes c : lista) {

                dados.addRow(new Object[]{
                    c.getId(),
                    c.getNOME(),
                    c.getDATAVENCIMENTO(),
                    c.getDATAVENCSISTEMA(),
                    c.getOBS(),
                    c.getFORMAPAG()

                });
            }

            DefaultTableModel dados2 = (DefaultTableModel) TpagSis.getModel();
            dados2.setNumRows(0);
            for (Clientes c : lista) {

                dados2.addRow(new Object[]{
                    c.getId(),
                    c.getNOME(),
                    c.getDATAVENCIMENTO(),
                    c.getDATAVENCSISTEMA(),
                    c.getOBS(),
                    c.getFORMAPAG()

                });
            }

        }


    }//GEN-LAST:event_txtPesquisaKeyPressed

    private void txtPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisaActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        if (txtPesquisa.getText().trim().isEmpty()) {
            listarClientesPagamanto();
            listarClientesPagamantoSis();

        }
        List<Clientes> lista = new ClientesDAO().consultarClientesPorNome1(txtPesquisa.getText());
        DefaultTableModel dados = (DefaultTableModel) TclientesPag.getModel();
        dados.setNumRows(0);
        for (Clientes c : lista) {

            dados.addRow(new Object[]{
                c.getId(),
                c.getNOME(),
                c.getDATAVENCIMENTO(),
                c.getDATAVENCSISTEMA(),
                c.getOBS(),
                c.getFORMAPAG()

            });
        }

        DefaultTableModel dados2 = (DefaultTableModel) TpagSis.getModel();
        dados2.setNumRows(0);
        for (Clientes c : lista) {

            dados2.addRow(new Object[]{
                c.getId(),
                c.getNOME(),
                c.getDATAVENCIMENTO(),
                c.getDATAVENCSISTEMA(),
                c.getOBS(),
                c.getFORMAPAG()

            });
        }

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaKeyReleased
        // TODO add your handling code here:

        List<Clientes> lista = new ClientesDAO().consultarClientesPorNome1("%" + txtPesquisa.getText() + "%");
        DefaultTableModel dados = (DefaultTableModel) TclientesPag.getModel();
        dados.setNumRows(0);
        for (Clientes c : lista) {

            dados.addRow(new Object[]{
                c.getId(),
                c.getNOME(),
                c.getDATAVENCIMENTO(),
                c.getDATAVENCSISTEMA(),
                c.getOBS(),
                c.getFORMAPAG()

            });
        }

        DefaultTableModel dados2 = (DefaultTableModel) TpagSis.getModel();
        dados2.setNumRows(0);
        for (Clientes c : lista) {

            dados2.addRow(new Object[]{
                c.getId(),
                c.getNOME(),
                c.getDATAVENCIMENTO(),
                c.getDATAVENCSISTEMA(),
                c.getOBS(),
                c.getFORMAPAG()

            });
        }

    }//GEN-LAST:event_txtPesquisaKeyReleased

    private void TclientesPagMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TclientesPagMouseClicked
        // TODO add your handling code here:
        Tmenu.setSelectedComponent(this.Pcadastro);
        txtCodigo.setText(TclientesPag.getValueAt(TclientesPag.getSelectedRow(), 0).toString());
        txtNome.setText(TclientesPag.getValueAt(TclientesPag.getSelectedRow(), 1).toString());
        txtDataVencimento.setText(TclientesPag.getValueAt(TclientesPag.getSelectedRow(), 2).toString().replace('-', '/'));
        txtDataSistema.setText(TclientesPag.getValueAt(TclientesPag.getSelectedRow(), 3).toString().replace('-', '/'));
        txtObs.setText(TclientesPag.getValueAt(TclientesPag.getSelectedRow(), 4).toString());
        comboPix.setSelectedItem(TclientesPag.getValueAt(TclientesPag.getSelectedRow(), 5).toString());
        
         int ano = 0;
        int mes = 0;
        int dia = 0;
        if(!txtNome.getText().trim().isEmpty()){
         ano = Integer.parseInt(txtDataVencimento.getText().substring(6,10));
            mes = Integer.parseInt(txtDataVencimento.getText().substring(3,5));
            dia = Integer.parseInt(txtDataVencimento.getText().substring(0,2));
            
            //pegar a data do sistema 
             String data = LocalDate.now().toString();
       int ano1 = Integer.parseInt(data.substring(0, 4)); //ano
       
       int mes1 = Integer.parseInt(data.substring(5, 7)); //mes
        
       int dia1 = Integer.parseInt(data.substring(8, 10)); //dia
      
       
       // calculo data final
       int anoFinal = ano1 - ano;
       if(anoFinal < 0){
          anoFinal = ano - ano1;
       }
         int mesFinal = mes - mes1; 
         if(mesFinal  < 0){
         mesFinal =  mes1 - mes;
         }
       int diaFinal = dia1 - dia;
       if(diaFinal < 0){
       diaFinal =  dia - dia1;
       }
       if(mes < mes1 && anoFinal == 1){
           
txtTempo.setText("Cliente à " + " " + anoFinal + " ano " + mesFinal + " meses e " + " " + diaFinal + " dias");

       }else if(mes > mes1 && anoFinal == 1){
       
             txtTempo.setText("Cliente à " + /*" " + anoFinal + " ano " +*/ mesFinal + " meses e " + " " + diaFinal + " dias");
       
       }else{
       
           txtTempo.setText("Cliente à " + mesFinal + " meses e " + " " + diaFinal + " dias" /*+ " " + anoFinal + " anos"*/);
       
       }
       
        }
    }//GEN-LAST:event_TclientesPagMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IPTVadministrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IPTVadministrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IPTVadministrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IPTVadministrator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfigDB();
                new IPTVadministrator().setVisible(true);
            }
        });

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Pcadastro;
    private javax.swing.JTable TclientesPag;
    private javax.swing.JTabbedPane Tmenu;
    private javax.swing.JTable TpagSis;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JCheckBox checkFilter;
    private javax.swing.JComboBox<String> comboPix;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private java.awt.Label label10;
    private java.awt.Label label11;
    private java.awt.Label label12;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCredito;
    private java.awt.Label txtCreditos;
    private java.awt.Label txtCusto;
    private javax.swing.JFormattedTextField txtDataSistema;
    private javax.swing.JFormattedTextField txtDataVencimento;
    private java.awt.Label txtLucro;
    private java.awt.TextField txtNome;
    private javax.swing.JTextArea txtObs;
    private javax.swing.JTextField txtPesquisa;
    private javax.swing.JLabel txtTempo;
    // End of variables declaration//GEN-END:variables
}
